name: ecocash
description: A comprehensive Dart SDK for integrating Ecocash payment services. Supports instant payments, transaction lookup, and refund processing with functional error handling.
version: 0.0.1
repository: https://github.com/iamngoni/ecocash
homepage: https://github.com/iamngoni/ecocash
documentation: https://github.com/iamngoni/ecocash#readme
issue_tracker: https://github.com/iamngoni/ecocash/issues

environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.0.1
  encrypt: ^5.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  localregex: ^4.0.5

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  test: ^1.19.2
  very_good_analysis: ^9.0.0

topics:
  - ecocash
  - payments
  - zimbabwe
  - fintech
  - flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
